### ISSUE TITLE
Loading Gosper Glider Gun not working

### ISSUE THREAD

**Issue by petrohi** [gheorghina/GameOfLife#3]
Tried loading Gosper Glider Gun in SizeOfTheUniverse branch and nothing happens.

**Comment by petrohi** [comment]
Also I see this in console:
![image](https://user-images.githubusercontent.com/464561/42787270-9fae5f80-890e-11e8-9a35-8dffd9f698f8.png)

**Comment by gheorghina** [comment]
Please make sure you also start the server side, which provides the json file with the alive cells for it:
The command can be found in the readme file of the project: 
json-server --watch src/data/GosperGliderGun.json --port 4000

**Comment by petrohi** [comment]
It works now--thanks!
