### ISSUE TITLE
~200 live cells slow down evolution considerably

### ISSUE THREAD

**Issue by petrohi** [gheorghina/GameOfLife#4]
![image](https://user-images.githubusercontent.com/464561/42802591-3e89ffd0-8958-11e8-8ded-acd807350029.png)

**Comment by petrohi** [comment]
Can we try limiting view to fixed size and see if this is rendering related or algorithm related?

**Comment by gheorghina** [comment]
I will :D ... the div approach is not the most performant one, but this is the level of UI skills I have.. The canvas approach would work better, but I did not focus on this. If you see it important, I can invest more also in this.

In the mean while, I will add some style to it to keep it fixed

**Comment by petrohi** [comment]
I suggest the simplest: to limit visible size to say 40x40. This way we will have constant rendering overhead and could truly test scalability of the algorithm as more live cells are added.

**Comment by gheorghina** [comment]
Done. I added input elements, you can choose the visible area then directly.
For now, the universe will not resize. 

Thank you!

**Comment by gheorghina** [comment]
Ah, I have to do one more small change

**Comment by gheorghina** [comment]
Now it is ok. You can set the initial X:Y position and the size of the visible square
